version: "3"

services:
  tpm-server:
    image: strongx509/tpm:latest
    container_name: tpm-server
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - ./strongswan.conf:/etc/strongswan.conf
